### ISSUE TITLE
attempt to index local 'location' error

### ISSUE THREAD

**Issue by kapral18** [sourcegraph/sg.nvim#209]
<img width="1492" alt="image" src="https://github.com/sourcegraph/sg.nvim/assets/1625373/bf731bd8-dcec-4430-9bd2-229c264160b2">

I don't have anything special in my config except just the plugin string for sg.nvim on top of latest lazyvim distro

**Comment by tjdevries** [comment]
Can you run `:checkhealth sg` for me? And please update to latest plugin, I just pushed some pretty big changes

**Comment by kapral18** [comment]
@tjdevries 
<img width="711" alt="image" src="https://github.com/sourcegraph/sg.nvim/assets/1625373/983b2ea6-1bfe-493d-807b-90d76420ceaa">

and for reference https://github.com/kapral18/dotfiles/blob/3b2e742c50c36c4d6d4e284af8bb9b8b90c2b3cd/home/dot_config/exact_nvim/exact_lua/exact_plugins/ai.lua#L105

**Comment by tjdevries** [comment]
The error is still happening?

**Comment by kapral18** [comment]
@tjdevries yepp

**Comment by kapral18** [comment]
> Can you run `:checkhealth sg` for me? And please update to latest plugin, I just pushed some pretty big changes

I noticed and I tried. I also nuked nvim instance with cache and state folders to make sure it's not affecting.

Still the same result unfortunately

**Comment by tjdevries** [comment]
Does this PR fix your problem? https://github.com/sourcegraph/sg.nvim/pull/221

**Comment by kapral18** [comment]
PR removes the errors, but at the same time going to definition doesn't happen as well

**Comment by amazr** [comment]
Also seeing this. Just logging the error in textDocument/definition gives: 'RPC[Error] code_name = ParseError, message = "No corresponding code intelligence"'. Some extra context that may or may not be relevant is that my sg url is not the default one.

**Comment by daniel-hernandez-sony** [comment]
I am also seeing this error with the default sourcegraph url and my health check looks healthy. Happy to give any extra info!

![image](https://github.com/sourcegraph/sg.nvim/assets/118762057/1cdbde1a-03cc-46b4-b85b-b2bfae702751)

**Comment by kqvanity** [comment]
I'm using it on a local instance, and getting the same error as well
